# relativeURLs = true
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
BaseURL = "https://nonotnones.github.io/ws-0001/"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "tuanatran.vn@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  
[Languages]
[Languages.en]
title = "Start with Amazon EFS file system ."
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://aws.amazon.com/blogs"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[Languages.vi]
title = "Bắt đầu với Amazon EFS file system "
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "http://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

